version: "3.7"
services:
  caddy:
    build:
      context: docker
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: bind
        source: ${CADDY_ROOT}
        target: /root/caddy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host

networks: 
  caddy-blog-network:
    attachable: true